development:
  adapter: postgresql
  database: todolist_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: todolist_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: todolist
  pool: 5
  timeout: 5000
